services:
  db:
    image: postgres:16
    container_name: aziz_animedb
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: aziz_grammydb
      # PostgreSQL optimizatsiya sozlamalari
      POSTGRES_INITDB_ARGS: "-E UTF8"
      POSTGRES_HOST_AUTH_METHOD: md5
    ports:
      - "5433:5432"
    volumes:
      - baza_data:/var/lib/postgresql/data
      - ./postgresql.conf:/etc/postgresql/postgresql.conf:ro
    command: 
      - "postgres"
      - "-c"
      - "config_file=/etc/postgresql/postgresql.conf"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d aziz_grammydb"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  app:
    build: .
    container_name: aziz_anime
    restart: always
    env_file:
      - .env
    expose:
      - "3001"
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "
        pnpm run build
        npx prisma generate &&
        npx prisma migrate deploy &&
        pnpm run start:prod
      "


volumes:
  baza_data:
